kind: Template
apiVersion: v1
metadata:
  name: wt-dashboard-api-build
  annotations:
    description: ""
    tags: wt-dashboard,python
    iconClass: icon-python
labels:
  template: python
parameters:
  - name: NAME
    displayName: Name
    description: The suffix for all created objects
    required: false
    value: wt-dashboard-api    
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    value: https://github.com/j-colaco-cgi/SBC_WaitTimeDashboard.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  - name: SOURCE_CONTEXT_DIR
    description: The source context directory.
    displayName: Source Context Directory
    required: false
    value: wtd-api
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: wt-dashboard-api
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: "${NAME}"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        app: "${NAME}"
    spec:
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Docker
        dockerStrategy:
          "dockerfilePath": "${DOCKER_FILE_PATH}"
          pullSecret:
            name: artifactory-creds              
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      resources:
        limits:
          cpu: '1'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 10
      failedBuildsHistoryLimit: 2
    status:
      lastVersion: 0